getenv = True

executable = /home/mbonse/2023_s4/50_code/venv_s4/bin/python
arguments = /home/mbonse/2023_s4/50_code/s4hci/scripts/naco_archive/compute_residuals_s4.py /fast/mbonse/NACO/30_data/$(dataset_name).hdf5

# Maximum expected execution time for the job, in seconds
MaxTime = 28800

# Commenting the two previous line and uncommenting this one would just kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

request_cpus = 2
request_gpus = 1
request_memory = 64000
requirements = (TARGET.CUDAGlobalMemoryMb > 40000) && (UtsnameNodename =!= "g207")

output = /fast/mbonse/NACO/70_results/logs/htcondor_s4_$(dataset_name).out
error  = /fast/mbonse/NACO/70_results/logs/htcondor_s4_$(dataset_name).err
log    = /fast/mbonse/NACO/70_results/logs/htcondor_s4_$(dataset_name).log

queue dataset_name from /fast/mbonse/NACO/70_results/datasets_100.txt