getenv = True

executable = /home/mbonse/2023_s4/50_code/venv_s4/bin/python
arguments = /home/mbonse/2023_s4/50_code/s4hci/scripts/contrast_grids/compute_residuals_pca.py /fast/mbonse/s4/30_data/$(dataset_name).hdf5 /fast/mbonse/s4/70_results/10_contrast_grids/$(dataset_name) $(exp_id) $(use_stacking)

# Maximum expected execution time for the job, in seconds
MaxTime = 86400

# Commenting the two previous line and uncommenting this one would just kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

request_cpus = 4
request_gpus = 1
request_memory = 30000
requirements = TARGET.CUDAGlobalMemoryMb > 20000

output = /fast/mbonse/s4/70_results/10_contrast_grids/logs/htcondor_pca_$(use_stacking)_$(dataset_name)_$(exp_id).out
error  = /fast/mbonse/s4/70_results/10_contrast_grids/logs/htcondor_pca_$(use_stacking)_$(dataset_name)_$(exp_id).err
log    = /fast/mbonse/s4/70_results/10_contrast_grids/logs/htcondor_pca_$(use_stacking)_$(dataset_name)_$(exp_id).log

queue dataset_name,exp_id,use_stacking from /fast/mbonse/s4/70_results/10_contrast_grids/02_pca_HD22049_303_199_C-0065_C_.txt