getenv = True

executable = /home/mbonse/2023_s4/50_code/venv_s4/bin/python
arguments = /home/mbonse/2023_s4/50_code/s4hci/scripts/contrast_grids/compute_residuals_s4.py /fast/mbonse/s4/30_data/$(dataset_name).hdf5 /fast/mbonse/s4/70_results/x1_fake_planet_experiments/$(dataset_name) $(exp_id) /fast/mbonse/s4/30_data/$(dataset_name).json

# Maximum expected execution time for the job, in seconds
MaxTime = 14400

# Commenting the two previous line and uncommenting this one would just kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

request_cpus = 2
request_gpus = 1
request_memory = 64000
requirements = (TARGET.CUDAGlobalMemoryMb > 40000) && (UtsnameNodename =!= "g207")

output = /fast/mbonse/s4/70_results/x1_fake_planet_experiments/logs/htcondor_s4_$(dataset_name)_$(exp_id).out
error  = /fast/mbonse/s4/70_results/x1_fake_planet_experiments/logs/htcondor_s4_$(dataset_name)_$(exp_id).err
log    = /fast/mbonse/s4/70_results/x1_fake_planet_experiments/logs/htcondor_s4_$(dataset_name)_$(exp_id).log

queue dataset_name,exp_id from /fast/mbonse/s4/70_results/x1_fake_planet_experiments/S4_HD22049_351_096_C-0679_A_.txt