getenv = True

executable = /home/mbonse/2023_s4/50_code/venv_s4/bin/python
arguments = /home/mbonse/2023_s4/50_code/s4hci/scripts/contrast_grids/compute_residuals_s4.py /fast/mbonse/s4/30_data/$(dataset_name).hdf5 /fast/mbonse/s4/70_results/x1_fake_planet_experiments/$(dataset_name) $(dit_psf_template) $(dit_science) $(fwhm) $(scaling_factor)

# Maximum expected execution time for the job, in seconds
MaxTime = 21600

# Commenting the two previous line and uncommenting this one would just kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

request_cpus = 32
request_gpus = 1
request_memory = 251072
requirements = (TARGET.CUDADeviceName == "NVIDIA H100 80GB HBM3") && (UtsnameNodename =!= "g211") && (UtsnameNodename =!= "g203") && (UtsnameNodename =!= "g212")

output = /fast/mbonse/s4/70_results/x1_fake_planet_experiments/logs/htcondor_baseline_$(dataset_name).out
error  = /fast/mbonse/s4/70_results/x1_fake_planet_experiments/logs/htcondor_baseline_$(dataset_name).err
log    = /fast/mbonse/s4/70_results/x1_fake_planet_experiments/logs/htcondor_baseline_$(dataset_name).log

queue dataset_name,dit_psf_template,dit_science,fwhm,scaling_factor from /fast/mbonse/s4/70_results/x1_fake_planet_experiments/baseline_experiments.txt