getenv = True

executable = /home/mbonse/2023_s4/50_code/venv_s4/bin/python
arguments = /home/mbonse/2023_s4/50_code/s4hci/scripts/contrast_grid/run_s4_contrast_grid.py /fast/mbonse/s4/30_data/$(dataset_name).hdf5 /fast/mbonse/s4/70_results/03_contrast_grid/finished_align_tests/$(dataset_name)/configs_cgrid/exp_ID_$(fake_planet_config_id).json $(reg_lambda) /fast/mbonse/s4/70_results/03_contrast_grid/finished_align_tests/$(dataset_name)/results/$(fake_planet_config_id)/$(shift_sel)/$(recenter) $(shift_sel) $(recenter)

# Maximum expected execution time for the job, in seconds
MaxTime = 86400

# Commenting the two previous line and uncommenting this one would just kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

request_cpus = 8
request_gpus = 1
request_memory = 65536
requirements = TARGET.CUDAGlobalMemoryMb > 38000

output = /fast/mbonse/s4/70_results/03_contrast_grid/finished_align_tests/$(dataset_name)/logs/htcondor_$(fake_planet_config_id)_$(shift_sel)_$(recenter).out
error  = /fast/mbonse/s4/70_results/03_contrast_grid/finished_align_tests/$(dataset_name)/logs/htcondor_$(fake_planet_config_id)_$(shift_sel)_$(recenter).err
log    = /fast/mbonse/s4/70_results/03_contrast_grid/finished_align_tests/$(dataset_name)/logs/htcondor_residuals.log

queue dataset_name,fake_planet_config_id,reg_lambda,shift_sel,recenter from /fast/mbonse/s4/70_results/03_contrast_grid/02_config_each_dataset_once.txt