getenv = True

executable = /home/mbonse/2023_s4/50_code/venv_s4/bin/python
arguments = /home/mbonse/2023_s4/50_code/s4hci/scripts/contrast_curves/compute_residuals_pre_trained.py /fast/mbonse/s4/30_data/$(dataset_name).hdf5 /fast/mbonse/s4/70_results/06_contrast_curves/02_cc_restored_models/ /fast/mbonse/s4/70_results/06_contrast_curves/01_train_each_model_once/$(dataset_name)/models/noise_model_fine_tuned.pkl /fast/mbonse/s4/70_results/06_contrast_curves/01_train_each_model_once/$(dataset_name)/models/normalization_model.pkl $(exp_id)

# Maximum expected execution time for the job, in seconds
MaxTime = 86400

# Commenting the two previous line and uncommenting this one would just kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

request_cpus = 8
request_gpus = 1
request_memory = 65536

output = /fast/mbonse/s4/70_results/06_contrast_curves/02_cc_restored_models/logs/htcondor_$(dataset_name)_$(exp_id).out
error  = /fast/mbonse/s4/70_results/06_contrast_curves/02_cc_restored_models/logs/htcondor_$(dataset_name)_$(exp_id).err
log    =/fast/mbonse/s4/70_results/06_contrast_curves/02_cc_restored_models/logs/htcondor_$(dataset_name)_$(exp_id).log

queue dataset_name,exp_id from /fast/mbonse/s4/70_results/06_contrast_curves/02_cc_restored_models/01_config_fake_planet_experiments.txt