getenv = True

executable = /home/mbonse/2023_s4/50_code/venv_s4/bin/python
arguments = /home/mbonse/2023_s4/50_code/s4hci/scripts/contrast_curves/run_s4_train_contrast_curve.py /fast/mbonse/s4/30_data/$(dataset_name).hdf5 /fast/mbonse/s4/70_results/06_contrast_curves/01_train_each_model_once/$(dataset_name)/

# Maximum expected execution time for the job, in seconds
MaxTime = 86400

# Commenting the two previous line and uncommenting this one would just kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

request_cpus = 8
request_gpus = 1
request_memory = 125536
requirements = TARGET.CUDAGlobalMemoryMb > 38000

output = /fast/mbonse/s4/70_results/06_contrast_curves/01_train_each_model_once/logs/htcondor_$(dataset_name).out
error  = /fast/mbonse/s4/70_results/06_contrast_curves/01_train_each_model_once/logs/htcondor_$(dataset_name).err
log    = /fast/mbonse/s4/70_results/06_contrast_curves/01_train_each_model_once/logs/htcondor_$(dataset_name).log

queue dataset_name from /fast/mbonse/s4/70_results/06_contrast_curves/01_train_each_model_once/01_config_each_dataset_once.txt