getenv = True

executable = /home/mbonse/2023_s4/50_code/venv_s4/bin/python
arguments = /home/mbonse/2023_s4/50_code/s4hci/scripts/implementation/s4_create_residuals_remask.py /fast/mbonse/s4/30_data/0100_C-0656-A/configs_cgrid/exp_ID_0000.json $(mask_size) /fast/mbonse/s4/30_data/EpsEri_0100_C-0656-A.hdf5 /fast/mbonse/s4/70_results/01_closed_form_hyperparameters/trained_models_norm/ /fast/mbonse/s4/70_results/01_closed_form_hyperparameters/residuals_norm_remask_3/ 3.0 $(lambda_reg)

# Maximum expected execution time for the job, in seconds
MaxTime = 12000

# Commenting the two previous line and uncommenting this one would just kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

request_cpus = 8
request_memory = 65536

output = /fast/mbonse/s4/70_results/01_closed_form_hyperparameters/logs_norm/htcondor_re_mask_residuals_$(mask_size)_$(lambda_reg).out
error  = /fast/mbonse/s4/70_results/01_closed_form_hyperparameters/logs_norm/htcondor_re_mask_residuals_$(mask_size)_$(lambda_reg).err
log    = /fast/mbonse/s4/70_results/01_closed_form_hyperparameters/logs_norm/htcondor_re_mask_residuals.log

queue mask_size,lambda_reg from /fast/mbonse/s4/70_results/01_closed_form_hyperparameters/residuals_norm_remask_3/config.txt