getenv = True

executable = /home/mbonse/2023_s4/50_code/venv_s4/bin/python
arguments = /home/mbonse/2023_s4/50_code/s4hci/scripts/partial_contrast_grid/compute_residuals_cadi.py /fast/mbonse/s4/30_data/$(dataset_name).hdf5 /fast/mbonse/s4/70_results/07_partial_contrast_grid/ $(exp_id)

# Maximum expected execution time for the job, in seconds
MaxTime = 86400

# Commenting the two previous line and uncommenting this one would just kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

request_cpus = 8
request_memory = 65536

output = /fast/mbonse/s4/70_results/07_partial_contrast_grid/logs/htcondor_cadi_$(dataset_name)_$(exp_id).out
error  = /fast/mbonse/s4/70_results/07_partial_contrast_grid/logs/htcondor_cadi_$(dataset_name)_$(exp_id).err
log    = /fast/mbonse/s4/70_results/07_partial_contrast_grid/logs/htcondor_cadi_$(dataset_name)_$(exp_id).log

queue dataset_name,exp_id from /fast/mbonse/s4/70_results/07_partial_contrast_grid/01_selection_HD22049_303_199_C-0065_C.txt