getenv = True

executable = /home/mbonse/2023_s4/50_code/venv_s4/bin/python
arguments = /home/mbonse/2023_s4/50_code/s4hci/scripts/partial_contrast_grid/compute_residuals_s4_pre_trained.py /fast/mbonse/s4/30_data/$(dataset_name).hdf5 /fast/mbonse/s4/70_results/07_partial_contrast_grid/ /fast/mbonse/s4/70_results/06_contrast_curves/01_train_each_model_once/$(dataset_name)/models/noise_model_fine_tuned.pkl /fast/mbonse/s4/70_results/06_contrast_curves/01_train_each_model_once/$(dataset_name)/models/normalization_model.pkl $(exp_id) $(setup)

# Maximum expected execution time for the job, in seconds
MaxTime = 7200

# Commenting the two previous line and uncommenting this one would just kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

request_cpus = 8
request_gpus = 1
request_memory = 125536
requirements = TARGET.CUDAGlobalMemoryMb > 80000

output = /fast/mbonse/s4/70_results/07_partial_contrast_grid/logs/htcondor_$(dataset_name)_$(exp_id)_$(setup).out
error  = /fast/mbonse/s4/70_results/07_partial_contrast_grid/logs/htcondor_$(dataset_name)_$(exp_id)_$(setup).err
log    = /fast/mbonse/s4/70_results/07_partial_contrast_grid/logs/htcondor_$(dataset_name)_$(exp_id)_$(setup).log

queue dataset_name,exp_id,setup from /fast/mbonse/s4/70_results/07_partial_contrast_grid/01_first_test_s4_HD22049_303_199_C-0065_C.txt